---
layout: post
title: "Automatic Question Generation"
root: ../../
---
In the lab meeting this week, 5th of Nov, Lydia will give a talk about Automatic Question Generation, integration of a Question Generation (QG) system with a learning environment and evaluation techniques for questions generated by a QG system.. The meeting will be at TASC1 9408 from 1030 hours.
